### PR TITLE
Menu and file IO cleanup, string escape fixes, import/export permission prompting

### LINKED ISSUE #2: Import/Export broken for Android 6.0 devices
My phone upgraded to Android 6.0 (API level 23) and I noticed the import/export feature stopped working.  I had previously exported my collections and upon importing I got an error message to the effect of "Error when opening input file for reading at <path>/database_version.txt".  Using the file explorer I was able to see that the file existed at the path specified, but the app wasn't able to access it.

Digging deeper I found that it was a permissions problem - starting in Android 6.0 (API level 23), apps must request access to external storage at run-time instead of install-time.  See [this link](https://developer.android.com/training/permissions/requesting.html).

### PR DESCRIPTION
**Pull request by sw23**
This pull request fixes #2

### CODE REVIEW

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 1]
```diff
@@ -130,19 +135,35 @@
...
+    // Note: Using constants instead of an enum based on this:
+    // https://developer.android.com/training/articles/memory.html#Overhead
+    // - Enums often require more than twice as much memory as static constants.
+    public final static int ADD_COLLECTION = 0;
+    public final static int REMOVE_COLLECTION = 1;
+    public final static int IMPORT_COLLECTIONS = 2;
+    public final static int EXPORT_COLLECTIONS = 3;
+    public final static int REORDER_COLLECTIONS = 4;
+    public final static int ABOUT = 5;
+
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Would you mind moving NUMBER_OF_COLLECTION_LIST_SPACERS to be defined near these?

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 2]
```diff
@@ -444,90 +462,80 @@ public void onClick(DialogInterface dialog, int item) {
...
-			f = new FileInputStream(file);
-			in_ = new InputStreamReader(f, "UTF8");
-			in = new BufferedReader(in_);
-		} catch (Exception e) {
-			showCancelableAlert(mRes.getString(R.string.error_open_file_reading, file.getAbsolutePath()));
-			return;
-		}
-    	
 		ArrayList<String[]> collectionInfo = new ArrayList<>();
+        String line;
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Should the line declaration be moved back into the 'try' block to limit its scope?

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 3]
```diff
@@ -613,27 +616,20 @@ private void handleImportCollectionsPart1(){
...
-    			showCancelableAlert(mRes.getString(R.string.error_open_file_reading, file.getAbsolutePath()));
-    			return;
-    		}
+    		in = openFileForReading(inputFile);
+    		if(in == null) return;
 
     		ArrayList<String[]> collectionContent = new ArrayList<>();
 
     		try {
-    			String line = in.readLine();
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Ah, I see why line's scope was increased.  I could go either way, although I think I'd prefer having two declarations of line that are both more narrowly scoped.  Thoughts?

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 4]
```diff
@@ -984,33 +959,145 @@ private void handleExportCollectionsPart2(){
...
+        InputStreamReader inputStreamReader;
+        BufferedReader bufferedReader;
+
+        try {
+            fileInputStream = new FileInputStream(file);
+            inputStreamReader = new InputStreamReader(fileInputStream, "UTF8");
+            bufferedReader = new BufferedReader(inputStreamReader);
+        } catch (Exception e) {
+            if(BuildConfig.DEBUG) {
+                Log.e(MainApplication.APP_NAME, e.toString());
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Let's have this log even in release mode - this way if we have a tech savvy user encounter this error (or, more likely, us) we can see what the issue is without having to install a debug build.  This case shouldn't be hit often, so it shouldn't put any strain on the log functionality

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 5]
```diff
@@ -984,33 +959,145 @@ private void handleExportCollectionsPart2(){
...
+
+        FileOutputStream fileOutputStream;
+        OutputStreamWriter outputStreamWriter;
+
+        try {
+            fileOutputStream = new FileOutputStream(file);
+            outputStreamWriter = new OutputStreamWriter(fileOutputStream, "UTF8");
+        } catch (Exception e) {
+            if(BuildConfig.DEBUG) {
+                Log.e(MainApplication.APP_NAME, e.toString());
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Same with this log

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 6]
```diff
@@ -984,33 +959,145 @@ private void handleExportCollectionsPart2(){
...
+
     private void showCancelableAlert(String text) {
 		mBuilder.setMessage(text).setCancelable(true);
 		AlertDialog alert = mBuilder.create();
 		alert.show();
 	}
 
+    private BufferedReader openFileForReading(File file){
+
+        FileInputStream fileInputStream;
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: These can be declared in the try block

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 7]
```diff
@@ -984,33 +959,145 @@ private void handleExportCollectionsPart2(){
...
+            }
+            return true;
+        }
+        return false;
+    }
+
+    private OutputStreamWriter openFileForWriting(File file){
+
+        FileOutputStream fileOutputStream;
+        OutputStreamWriter outputStreamWriter;
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: These can be declared in the try block (and outputStreamWriter returned from there)

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 8]
```diff
@@ -984,33 +959,145 @@ private void handleExportCollectionsPart2(){
...
+    }
+
+    private boolean closeInputFile(BufferedReader in, File file, boolean silent){
+        try {
+            in.close();
+        } catch (IOException e) {
+            if(!silent){
+                showCancelableAlert(mRes.getString(R.string.error_closing_input_file, file.getAbsolutePath()));
+            }
+            return true;
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: I wonder if it would make more sense to have close return false in the error case and true otherwise... That way the return value would indicate whether the close succeeded.  Thoughts?

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 9]
```diff
@@ -984,33 +959,145 @@ private void handleExportCollectionsPart2(){
...
+        }
+        return outputStreamWriter;
+    }
+
+    private boolean closeOutputFile(OutputStreamWriter out, File file){
+        try {
+            out.close();
+        } catch (IOException e) {
+            showCancelableAlert(mRes.getString(R.string.error_closing_output_file, file.getAbsolutePath()));
+            return true;
```
Comment (anwilli5) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Same thought here about switching true/false

File: app/src/main/java/com/spencerpages/MainActivity.java (hunk 3 above)
Comment (sw23) [inline app/src/main/java/com/spencerpages/MainActivity.java]: I considered that but was swayed given that a few other file-related variables are shared across files for the import within the scope.  I don't have a strong preference either way though

File: app/src/main/java/com/spencerpages/MainActivity.java (hunk 8 above)
Comment (sw23) [inline app/src/main/java/com/spencerpages/MainActivity.java]: I couldn't make up my mind on this as well.  I'll switch it

File: app/src/main/java/com/spencerpages/MainActivity.java [hunk 10]
```diff
@@ -130,19 +135,35 @@
...
+
+    // App permission requests
+    private final static int IMPORT_PERMISSIONS_REQUEST = 0;
+    private final static int EXPORT_PERMISSIONS_REQUEST = 1;
+
     @Override
     public void onCreate(Bundle savedInstanceState) {
     	super.onCreate(savedInstanceState);
-    	
+        Log.d(MainApplication.APP_NAME, "onCreate");
```
Comment (sw23) [inline app/src/main/java/com/spencerpages/MainActivity.java]: Didn't mean to leave this in! :)
